ALTER TABLE folha_pagamento
ADD COLUMN IF NOT EXISTS plano_saude DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS convenio_escolhido TEXT,
ADD COLUMN IF NOT EXISTS faixa_etaria TEXT,
ADD COLUMN IF NOT EXISTS vl_100_amil DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS vl_empresa_amil DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS vl_func_amil DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS amil_saude_dep DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS odont_func DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS odont_dep DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS idade INTEGER DEFAULT 0;
